# print("Starting up the program...")
# print("Doing some setup...")
# print "Hello!"
# print("All done.")
# x = 5
# print("x is", x)
# y = 7
# print("y is", y)
# x = "hello"
# print("now x is", x)
# print(x + 10)
# print("This line never runs")
# print("Starting up the program...")
# print("Doing some setup...")
# Print("Hello!")
# print("All done.")
# print("Starting...")
# print(score)
# print("This never runs")
# print("Starting...")
# age: int
# print(age)

# x=5
# if x>5:
#     print(y)
# else:
#     print("He he")
# print("Calculating the class average...")
# total = 100
# count = 0
# print(total / count)
# print("Done")
# x = 35
# y = 19
# remainder = x - int(x/y) * y
# print(remainder)
# print(450.0 % 360.0)
# print(26.5 % 24.0)
# print(3.75 % 1.0)
# print(7.5 / 2)
# print(7.5 // 2)
# print(7.5 % 2)
# print(-7.5 // 2)
# print(-7.5 % 2)
# print(7.5 % -2)
# print(24 // 6.0 )
# print(-7 // 2   )  
# print(5.5 % 2.0 )    




# print(type(7.5 / 2))
# print(type(7.5 // 2))
# print(type(7.5 % 2))
# print(type(-7.5 // 2))
# print(type(-7.5 % 2))
# print(type(7.5 % -2))
# print(type(24 // 6.0 ))
# print(type(-7 // 2   )  )
# print(type(5.5 % 2.0 ))    



# print(2 + 3 * 4)
# print((2 + 3* 2-3) * 4)
# print( 2 + 3 * 4 ** 2)
# print(12 / 2 ** 2 + 1 )
# print(  7 // 2 + 7 % 2   )
# a = 5;b=2
# print(  a + b * a ** b  )
# print( (a + b) * a ** b )
# print( 1.5 * 2 + 1 )


# print(2 ** 100)
# print(2 ** 1000)
# print(23%-6)


# print((-7 * -7) ** 0.5)
# print(abs(-7))
# # print(abs(-3.5))
                                    #    "Bankers Rounding"

# print(round(0.5))
# print(round(1.5))      
# print(round(2.7))
# print(round(3.5))
# print(round(3.14159, 2))

print(pow(0.2, 3))
print(max(3, 7, 2))
print(min(3, 7, 2))


import math

print(math.sqrt(16))