# print("Python", "is", "fun") 
# print("2026", "08", "25", sep="-") 
# print("Loading", end="...") 
# print("Done!") 
# print("Line one\nLine two\nLine three") 
# print("Name\tCity\tCourse") 
# print("Aman\tDelhi\tCSE") 
# print("Your name is:", input("Enter your name: ")) 
# print("==== WELCOME ====\nName:\tRiya\nHobby:\tPainting\n==================")
# name = input("Enter your name: ")
# city = input("Enter your city: ")
# hobby = input("Enter your hobby: ")

# print("=====WELCOME=====\nName:" \tname "\nCity:\tcity\nHobby:\thobby\n===================")
print(6.8%2)
